### ISSUE TITLE
cuda memory insufficient

### ISSUE THREAD

**Issue by evercherish** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#12]
Hi, thanks for your work! 
I am trying test.py on gpu, but got error "cuda out of memory".(rtx 2080ti)
Any solution could solve this?
thanks!

**Comment by lavi135246** [comment]
As far as I know and with my limited hardware (GTX 1080), I am not able to solve this in any way.
However, you may take a look at the discussion in the PyTorch forum.
https://discuss.pytorch.org/t/solved-pytorch-conv2d-consumes-more-gpu-memory-than-tensorflow/28998

I am closing this since it is more of a PyTorch issue.
