### ISSUE TITLE
Where is the slice operation in test code?

### ISSUE THREAD

**Issue by YDDDDG** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#16]
Hello,
You mentioned that you slice the original input images into small pieces(1024*1024) in readme, however, I cannot find the corresponding operations in the test code. Would you please tell me where is the slice operation?  thank you~

**Comment by lavi135246** [comment]
Hi @YDDDDG ,

Since I only wanted to make sure the result was correct, the slice operation was done half manually. And as you see, slicing the image leads to some quality issue and the code I wrote was not clean, and therefore I didn't upload it. If you have a better GPU, you can process the whole image without any problem, or just process it on a CPU.
