### ISSUE TITLE
About the codes

### ISSUE THREAD

**Issue by Sun-Fan** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#2]
Thanks for releasing the code. I want to know if you have got the results of the paper when using the pytorch codes.

**Comment by ninetf135246** [comment]
Hi @Sun-Fan ,
If you read the [readme](https://github.com/ninetf135246/pytorch-Learning-to-See-in-the-Dark/blob/master/README.md) carefully, you may see that the result is shown in the figure at the end of the readme. Since Pytorch somehow needs more GPU resources than tensorflow in this case, I could only slice the original input images into small pieces before feeding them into the model. I am quite sure that the model will perform well if it takes in whole images.
Also, I have provided a [trained model](https://drive.google.com/file/d/1qVYtDEObRAox8SDH4Tbqs2s117v7tFWG/view) for sony dataset. You may download it and try by yourself.
