### ISSUE TITLE
Considering your failure case

### ISSUE THREAD

**Issue by chrismgeorge** [ninetf135246/pytorch-Learning-to-See-in-the-Dark#9]
I'm pretty sure you can just pass the whole image into the network for testing, so you wouldn't need to slice it up.

**Comment by ninetf135246** [comment]
Hi @chrismgeorge ,
Since I haven't touched this project for a long time, I am wondering what is your environmental configuration. It would be kind if you can provide me information about the version of CUDA and PyTorch and your GPU model so that I can decide whether to fix this issue.

Also, pr is welcomed :)

**Comment by ninetf135246** [comment]
I am now using CPU for testing and fixed the memory insufficient issue in GPU
